"""empty message

Revision ID: 5c4079dd832e
Revises: 67a566c46e86
Create Date: 2019-04-05 14:23:49.832547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c4079dd832e'
down_revision = '67a566c46e86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('about_me', sa.Text(), nullable=True))
    op.add_column('customers', sa.Column('last_seen', sa.DateTime(), nullable=True))
    op.add_column('customers', sa.Column('location', sa.String(length=64), nullable=True))
    op.add_column('customers', sa.Column('member_since', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'member_since')
    op.drop_column('customers', 'location')
    op.drop_column('customers', 'last_seen')
    op.drop_column('customers', 'about_me')
    # ### end Alembic commands ###
