"""empty message

Revision ID: dc35088ee503
Revises: 55b97b41214a
Create Date: 2019-04-29 10:29:31.559486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc35088ee503'
down_revision = '55b97b41214a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('products', sa.Column('image', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'image')
    op.drop_column('products', 'description')
    # ### end Alembic commands ###
